### ISSUE TITLE
We want wikipedia search

### ISSUE THREAD

**Issue by hugefiver** [CSUSTers/csust_bot#5]
我们想要Wikipedia的摘要功能但是不会写。 @YuJuncen 来写一个吧，大佬

**Comment by YuJuncen** [comment]
![84e6eec8fe67b8220c77a509be6faca5](https://user-images.githubusercontent.com/36239017/42041175-eeabb1a8-7b23-11e8-886b-cf424ae77abc.jpg)

**Comment by hugefiver** [comment]
@YuJuncen emmm,没有
